baseurl = "https://www.thebentarchive.net/"
title = "The Bent Archive"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "The Bent Archive"
    avatar = "avatar.png"
    # avatarDescription = "HJB"
    favicon = "favicon.png"
    description = """
        I'm Hal Bender. Welcome to my archive.
        <h2><a href="https://www.thebentarchive.net/fiction/">Fiction</a> · <a href="https://www.thebentarchive.net/gallery/">Gallery</a></h2>
    """
    publicationYear = "2021"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    custom_css = ["/css/style.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "ao3"
    # name = "AO3" #If display text link, cancel comment out
    pre = "<i class='fa fa-book fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "https://archiveofourown.org/users/hjbender"
    weight = 10

[[menu.main]]
    identifier = "tumblr"
    # name = "Tumblr"
    pre = "<i class='fab fa-tumblr fa-lg'></i>"
    url = "https://hjbender.tumblr.com"
    weight = 20

[[menu.main]]
    identifier = "twitter"
    # name = "Twitter"
    pre = "<i class='fab fa-twitter fa-lg'></i>"
    url = "https://twitter.com/hjbender"
    weight = 30

[[menu.main]]
    identifier = "about"
    # name = "About"
    pre = "<i class='fa fa-user fa-lg'></i>"
    url = "https://hjbender.carrd.co/#more"
    weight = 40
